// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSDQoBCSEWbWNV0Q72Cqj9qYwfRSpW51U',
    appId: '1:755773041370:web:a8adc87600902003f1d3e3',
    messagingSenderId: '755773041370',
    projectId: 'mungyeong-b77e4',
    authDomain: 'mungyeong-b77e4.firebaseapp.com',
    storageBucket: 'mungyeong-b77e4.appspot.com',
    measurementId: 'G-RC1B04CRPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT5y-Oc3myGvAo2EQrzJuJgVppCVUPpR8',
    appId: '1:755773041370:android:b0a83cba60ffd293f1d3e3',
    messagingSenderId: '755773041370',
    projectId: 'mungyeong-b77e4',
    storageBucket: 'mungyeong-b77e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbP2dMderrdKlQ16WfobLJHI6yMKApclw',
    appId: '1:755773041370:ios:a17d4f4510f5e9b2f1d3e3',
    messagingSenderId: '755773041370',
    projectId: 'mungyeong-b77e4',
    storageBucket: 'mungyeong-b77e4.appspot.com',
    iosBundleId: 'com.example.push.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbP2dMderrdKlQ16WfobLJHI6yMKApclw',
    appId: '1:755773041370:ios:a17d4f4510f5e9b2f1d3e3',
    messagingSenderId: '755773041370',
    projectId: 'mungyeong-b77e4',
    storageBucket: 'mungyeong-b77e4.appspot.com',
    iosBundleId: 'com.example.push.pushApp',
  );
}
