// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqt0y2jVoAJDW4v_uLQ4vMZHLc3xUbgiE',
    appId: '1:720599880060:web:1a9c87883c4e032bcd94f9',
    messagingSenderId: '720599880060',
    projectId: 'fcm-push-learn',
    authDomain: 'fcm-push-learn.firebaseapp.com',
    storageBucket: 'fcm-push-learn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjw8TAZHvuw7nmYZJKXf4AR_CXl1aAKDc',
    appId: '1:720599880060:android:b39c5948ed592b8bcd94f9',
    messagingSenderId: '720599880060',
    projectId: 'fcm-push-learn',
    storageBucket: 'fcm-push-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_1i1SGhDys5R8mkIuRcDht7NsaWTd24',
    appId: '1:720599880060:ios:30dec6dee6d659dacd94f9',
    messagingSenderId: '720599880060',
    projectId: 'fcm-push-learn',
    storageBucket: 'fcm-push-learn.appspot.com',
    iosBundleId: 'com.example.push.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_1i1SGhDys5R8mkIuRcDht7NsaWTd24',
    appId: '1:720599880060:ios:30dec6dee6d659dacd94f9',
    messagingSenderId: '720599880060',
    projectId: 'fcm-push-learn',
    storageBucket: 'fcm-push-learn.appspot.com',
    iosBundleId: 'com.example.push.pushApp',
  );
}
